artifact_uri: file:///Users/didodeboodt/Documents/Projects/Retail_Forecasting_Project/01_Notebooks/../02_MLflow/576372739668588213/359d45a2b644497388fabf11c4d815ad/artifacts
end_time: 1749742236745
entry_point_name: ''
experiment_id: '576372739668588213'
lifecycle_stage: active
run_id: 359d45a2b644497388fabf11c4d815ad
run_name: ARIMA_Model
source_name: ''
source_type: 4
source_version: ''
start_time: 1749742229648
status: 3
tags: []
user_id: didodeboodt
