artifact_location: file:///Users/didodeboodt/Documents/Projects/Retail_Forecasting_Project/01_Notebooks/../02_MLflow/576372739668588213
creation_time: 1749732570099
experiment_id: '576372739668588213'
last_update_time: 1749732570099
lifecycle_stage: active
name: Retail_Forecasting
