artifact_uri: file:///Users/didodeboodt/Documents/Projects/Retail_Forecasting_Project/01_Notebooks/../02_MLflow/576372739668588213/600a80bf0a5b4ffdadd20d1895c3ea54/artifacts
deleted_time: 1749742252329
end_time: 1749742026765
entry_point_name: ''
experiment_id: '576372739668588213'
lifecycle_stage: deleted
run_id: 600a80bf0a5b4ffdadd20d1895c3ea54
run_name: ARIMA_Model
source_name: ''
source_type: 4
source_version: ''
start_time: 1749742026749
status: 4
tags: []
user_id: didodeboodt
