artifact_uri: file:///Users/didodeboodt/Documents/Projects/Retail_Forecasting_Project/01_Notebooks/../02_MLflow/576372739668588213/370aa152a6d54592a6e8376f53e14333/artifacts
end_time: 1749733697652
entry_point_name: ''
experiment_id: '576372739668588213'
lifecycle_stage: active
run_id: 370aa152a6d54592a6e8376f53e14333
run_name: XGBoost_Randomized_Search
source_name: ''
source_type: 4
source_version: ''
start_time: 1749733694448
status: 3
tags: []
user_id: didodeboodt
